apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami
resources:
- namespace.yaml
- ../../../base/whoami

patches:
- target:
    kind: Ingress
    name: whoami
  path: ingress-patch.yaml
