apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth
type: Opaque
data:
  CLIENT_SECRET: VktwVUYxVkp0Y1BHU1ZwQU1id1EwdmRHSm9BNFRQaE8=
  SECRET: Nzk5ZGNlZjM4MzdhMzJlN2YxZWE1ZTgyNDY1NDJhMTU=
  # ENCRYPTION_KEY former SESSION_KEY
  ENCRYPTION_KEY: TDlWVm5kUVRpOGNEZTRCakliZlhISE9veVFqWFNVU1E=
