apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: jaeger-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
      interval: 12h
