apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-crds
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  # dependsOn:
  # - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: keycloak-k8s-resources-crds
  path: ./kubernetes
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
  - name: keycloak-crds
  sourceRef:
    kind: GitRepository
    name: keycloak-k8s-resources
  path: ./kubernetes
  prune: true
  wait: true
