apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: keycloak-k8s-resources
spec:
  interval: 24h
  ref:
    tag: "22.0.3"
  url: https://github.com/keycloak/keycloak-k8s-resources.git
