apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-depl
  namespace: keycloak-git
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: keycloak-k8s-resources
  path: ./kubernetes
  prune: true
  wait: true
