apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ngrok-ingress-controller
spec:
  chart:
    spec:
      chart: kubernetes-ingress-controller
      version: v0.11.0
      sourceRef:
        kind: HelmRepository
        name: ngrok
  interval: 15m
  timeout: 5m
  values:
    credentials:
      secret:
        name: ngrok-ingress-controller-credentials

