apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ngrok-ingress-controller
spec:
  chart:
    spec:
      chart: ngrok-ingress-controller
      version: v1.5.1
      sourceRef:
        kind: HelmRepository
        name: ngrok
  interval: 15m
  timeout: 5m
  install:
    createNamespace: true
  values:
    credentials:
      secret:
        name: ngrok-ingress-controller-credentials

