apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-ingress-controller-credentials
type: Opaque
data:
  API_KEY: MlZmajdZUEg5YmZ1N1l2Q1Jqc29zRlVYa2ViXzdGNkpDZXdUMXlKb1AxQnA1VVp6ZA==
  AUTHTOKEN: MlZYYmU2cXV4c2pieFl0a3Z1WWdmMFNUTExHXzZDOU5QRHdGSnQyWkVSNWo0MUNGeA==
