apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-ingress-controller-credentials
type: Opaque
data:
  API_KEY: dXNyXzJWWGJlQnltTzNYMGJZUXoycjk3WXpsb245cgo=
  AUTHTOKEN: MlZYYmU2cXV4c2pieFl0a3Z1WWdmMFNUTExHXzZDOU5QRHdGSnQyWkVSNWo0MUNGeAo=
