apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whoami
resources:
- namespace.yaml
- ../../../base/whoami
- ingress-local.yaml

patches:
- target:
    kind: Ingress
    name: whoami
  path: ingress.yaml
