apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: joern.arne
  labels:
    app: external-sso
spec:
  realmSelector:
    matchLabels:
      app: external-sso
  user:
    username: joern.arne
    firstName: Jörn Arne
    lastName: Göttig
    email: joern.arne@gmail.com
    enabled: True
    emailVerified: True
    credentials:
    - type: password
      value: vieTu0xi
    realmRoles:
    - offline_access
    - uma_authorization
    clientRoles:
      account:
      - manage-account
      - view-profile
      realm-management:
      - manage-users
      - view-users
      - query-users
      - create-client
