apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
spec:
  chart:
    spec:
      chart: authelia
      version: v0.8.57
      sourceRef:
        kind: HelmRepository
        name: authelia
  interval: 1h
  timeout: 5m
  values:
    domain: authelia.127.0.0.1.nip.io
    ingress:
      subdomain: auth
