kind: Deployment
apiVersion: apps/v1
metadata:
  name: keycloak
  labels:
    app: keycloak

spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: keycloak
        # image: sleighzy/keycloak:16.1.0-arm64
        image: quay.io/keycloak/keycloak:22.0.3
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        env:

        # - name: KEYCLOAK_IMPORT
        #   value: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled

        - name: KEYCLOAK_USER
          valueFrom:
            configMapKeyRef:
              name: keycloak
              key: KEYCLOAK_USER

        - name: KEYCLOAK_MGMT_USER
          valueFrom:
            configMapKeyRef:
              name: keycloak
              key: KEYCLOAK_MGMT_USER

        - name: JAVA_OPTS_APPEND
          valueFrom:
            configMapKeyRef:
              name: keycloak
              key: JAVA_OPTS_APPEND

        - name: PROXY_ADDRESS_FORWARDING
          valueFrom:
            configMapKeyRef:
              name: keycloak
              key: PROXY_ADDRESS_FORWARDING

        - name: KEYCLOAK_LOGLEVEL
          valueFrom:
            configMapKeyRef:
              name: keycloak
              key: KEYCLOAK_LOGLEVEL

        - name: ROOT_LOGLEVEL
          valueFrom:
            configMapKeyRef:
              name: keycloak
              key: ROOT_LOGLEVEL

        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: KEYCLOAK_PASSWORD

        - name: KEYCLOAK_MGMT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: KEYCLOAK_MGMT_PASSWORD

        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: keycloak
        #       key: POSTGRES_PASSWORD

        # - name: DB_VENDOR
        #   valueFrom:
        #     configMapKeyRef:
        #       name: keycloak
        #       key: DB_VENDOR

        # - name: DB_ADDR
        #   valueFrom:
        #     configMapKeyRef:
        #       name: keycloak
        #       key: POSTGRES_HOST

        # - name: DB_PORT
        #   valueFrom:
        #     configMapKeyRef:
        #       name: keycloak
        #       key: POSTGRES_PORT

        # - name: DB_USER
        #   valueFrom:
        #     configMapKeyRef:
        #       name: keycloak
        #       key: POSTGRES_USER

        # - name: DB_DATABASE
        #   valueFrom:
        #     configMapKeyRef:
        #       name: keycloak
        #       key: POSTGRES_DATABASE


        volumeMounts:
        ## volume mount keycloak-data required when using H2 database
        - name: keycloak-data
          mountPath: /opt/jboss/keycloak/standalone/data

        - name: realm-export
          mountPath: /opt/jboss/keycloak/imports

      ## volume required when using H2 database
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-pvc
      - name: realm-export
        configMap:
          name: realm-export
