apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: op-connect-operator
spec:
  values:
    operator:
      create: true
      token:
        name: onepassword-token
        key: token
    connect:
      credentialsName: op-credentials
      credentialsKey: 1password-credentials.json
