apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgress-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: pgo
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: postgress-operator
      interval: 12h
