apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  template:
    metadata:
      labels:
        app: traefik-forward-auth
        # annotations:
        #   container.apparmor.security.beta.kubernetes.io/traefik-forward-auth: runtime/default
    spec:
      containers:
      - name: traefik-forward-auth
        # image: thomseddon/traefik-forward-auth:2.2.0-arm
        image: joernarne/traefik-forward-auth:3.1.0
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          runAsGroup: 65534
          capabilities:
            drop:
            - ALL
        livenessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 4181
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            memory: '10Mi'
            cpu: '100m'
        ports:
        - name: http
          containerPort: 4181
        env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth
              key: CLIENT_SECRET
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth
              key: SECRET
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: traefik-forward-auth
              key: ENCRYPTION_KEY
        - name: DEFAULT_PROVIDER
          valueFrom:
            configMapKeyRef:
              name: traefik-forward-auth
              key: DEFAULT_PROVIDER
        - name: PROVIDER_URI
          valueFrom:
            configMapKeyRef:
              name: traefik-forward-auth
              key: PROVIDER_URI
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: traefik-forward-auth
              key: CLIENT_ID
        - name: INSECURE_COOKIE
          valueFrom:
            configMapKeyRef:
              name: traefik-forward-auth
              key: INSECURE_COOKIE
        - name: COOKIE_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: traefik-forward-auth
              key: COOKIE_DOMAIN
        - name: DOMAINS
          valueFrom:
            configMapKeyRef:
              name: traefik-forward-auth
              key: DOMAINS
        - name: AUTH_HOST
          valueFrom:
            configMapKeyRef:
              name: traefik-forward-auth
              key: AUTH_HOST
        - name: URL_PATH
          valueFrom:
            configMapKeyRef:
              name: traefik-forward-auth
              key: URL_PATH
