apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-initial-admin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-op-connect
  target:
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: k3d-dev.lessingstrasse.org_SSO_admin
