apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-op-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: keycloak-infrastructure
      property: db_username
  - secretKey: password
    remoteRef:
      key: keycloak-infrastructure
      property: db_password
