apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: v1.13.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 1h
  timeout: 5m
  releaseName: cert-manager
  valuesKey:
    installCRDs: true

  # valuesFrom:
  # - kind: ConfigMap
  #   name: cert-manager-helm-chart-value-overrides
  #   valuesKey: values.yaml # This is the default, but best to be explicit for clarity
