apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: joern.arne@gmail.com
    disableAccountKeyGeneration: true
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      # selector:
      #   dnsNames:
      #   - 'k3s.lessingstrasse.org'
      #   - '*.k3s.lessingstrasse.org'
