apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: op-eso
resources:
- ../../../base/op-eso

patches:
- target:
    kind: ClusterSecretStore
    name: css-op-connect
  path: css-op-connect-patch.yaml
