apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: v1.13.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 1h
  timeout: 5m
  releaseName: cert-manager
  values:
    installCRDs: true
