apiVersion: v1
kind: Secret
metadata:
  name: keycloak-initial-admin
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak
data:
  username: YWRtaW5Aa2V5Y2xvYWs= # admin@keycloak
  password: S01LOHlzZ1I2ODI5a1ouX0p3b2hGYUFF # KMK8ysgR6829kZ._JwohFaAE
type: kubernetes.io/basic-auth
