apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: op-keycloak
resources:
- certificate.yaml
- ingress-k3d.yaml
- ../../../base/keycloak-instance

patches:
- path: keycloak-patch.yaml
  target:
    kind: Keycloak
