apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: letsencrypt-staging-issuer-account-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-op-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: tls.key
    remoteRef:
      key: cert-manager-test
      property: tls_key
