apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: traefik-forward-auth
  labels:
    app: external-sso
spec:
  realmSelector:
    matchLabels:
      app: external-sso
  client:
    clientId: traefik-forward-auth
    secret: VKpUF1VJtcPGSVpAMbwQ0vdGJoA4TPhO
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    redirectUris:
    - https://auth.k3s.lessingstrasse.org/_oauth
    webOrigins:
    - '/*' # redirectUris
    defaultClientScopes:
    - email
    - profile
    - roles
    - web-origins
    optionalClientScopes:
    - address
    - microprofile-jwt
    - offline_access
    - phone
