apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: pgo
      version: "5.4.2"
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
      interval: 12h
