# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: whoami-ingress
#   annotations:
#     cert-manager.io/cluster-issuer: pebble-issuer
# spec:
#   ingressClassName: traefik
#   tls:
#   - hosts:
#     - whoami.127.0.0.1.nip.io
#     secretName: whoami.127.0.0.1.nip.io
#   rules:
#   - host: whoami.127.0.0.1.nip.io
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: whoami-svc
#             port:
#               number: 80
# ---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-k3d-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: traefik
  rules:
  - host: whoami.k3d.lessingstrasse.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami-svc
            port:
              number: 80
  tls:
  - hosts:
    - whoami.k3d.lessingstrasse.org
    secretName: whoami-k3d-lessingstrasse-org
