apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-k3d-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: whoami.k3d.lessingstrasse.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whoami-svc
            port:
              number: 80
