apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  http:
    httpEnabled: true
  #   tlsSecret: example-tls-secret
  hostname:
    hostname: keycloak-test.k3d.lessingstrasse.org
    # strict: false
    # strictBackchannel: false
