apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
spec:
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
      hosts:
      - host: weave.127.0.0.1.nip.io
        paths:
        - path: /
          pathType: ImplementationSpecific
      - host: weave.k3d-example.lessingstrasse.org
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - hosts:
        - weave.k3d-example.lessingstrasse.org
        secretName: weave.k3d-example.lessingstrasse.org

