apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: css-op-connect
  target:
    creationPolicy: Owner
  data:
  - secretKey: api-token
    remoteRef:
      key: cloudflare-api
      property: api-token

