apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/tmp/k3d-dev-vol/keycloak-pv"
