apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: op-keycloak
resources:
- ../../../base/traefik-forward-auth

patches:
- target:
    kind: Ingress
    name: traefik-forward-auth
  path: ingress-patch.yaml

configMapGenerator:
- name: traefik-forward-auth
  behavior: merge
  literals:
  - COOKIE_DOMAIN=k3d-example.lessingstrasse.org
  - DOMAINS=k3d-example.lessingstrasse.org
  - AUTH_HOST=auth.k3d-example.lessingstrasse.org
  - PROVIDER_URI=https://keycloak.k3d-example.lessingstrasse.org/realms/k3d-example
  - LOG_LEVEL=info
