apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitnami
spec:
  chart:
    spec:
      chart: redis
      version: v18.0.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1h
  timeout: 5m
