apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
spec:
  secretName: << example.com >>
  dnsNames:
  - << example.com >>
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
