apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: op-keycloak
resources:
- ../../../base/keycloak-instance

patches:
- path: keycloak-patch.yaml
  target:
    kind: Keycloak

- path: certificate-patch.yaml
  target:
    name: keycloak
    kind: Certificate

- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: keycloak

- target:
    kind: KeycloakRealmImport
    name: keycloak-realm-import
  path: keycloak-realm-import-patch-users.yaml

- target:
    kind: KeycloakRealmImport
    name: keycloak-realm-import
  path: keycloak-realm-import-patch-clients.yaml

- target:
    kind: KeycloakRealmImport
    name: keycloak-realm-import
  path: keycloak-realm-import-patch-json.yaml

