# realm:
- op: replace
  path: /spec/realm/realm
  value: k3d-dev


# clientId: account
- op: replace
  path: /spec/realm/clients/0/baseUrl
  value: /realms/k3d-dev/account/

- op: replace
  path: /spec/realm/clients/0/redirectUris
  value:
  - /realms/k3d-dev/account/*


# clientId: account-console
- op: replace
  path: /spec/realm/clients/1/baseUrl
  value: /realms/k3d-dev/account/

- op: replace
  path: /spec/realm/clients/1/redirectUris
  value:
  - /realms/k3d-dev/account/*
