apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: op-1p-connect
spec:
  interval: 1h
  chart:
    spec:
      chart: connect
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: op-1p-connect
      interval: 12h

  values:
    operator:
      create: false
      token:
        name: onepassword-token-kustomize
        key: token
    connect:
      create: true
      credentialsName: op-credentials-kustomize
      credentialsKey: 1password-credentials.json
