apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-red
resources:
- namespace.yaml
- pv.yaml
- pvc.yaml
- ../../../base/node-red

patches:
- target:
    kind: Ingress
    name: node-red
  path: ingress-patch.yaml
