# This is a realm definition handled by the new Keycloak Operator
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: example-keycloakrealm
spec:
  keycloakCRName: keycloak
  realm:
    id: basic-new-import
    realm: basic-new-import
