apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pebble-issuer
spec:
  acme:
    skipTLSVerify: true
    email: example@example.com
    server: https://pebble-svc.pebble:14000/dir
    privateKeySecretRef:
      name: pk-pebble-issuer
    solvers:
    - http01:
        ingress:
          class: traefik
