apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: locust
resources:
- namespace.yaml
- service.yaml
- ingress.yaml
- deployment-master.yaml
- deployment-slave.yaml


configMapGenerator:
- name: scripts-cm
  files:
  - locustfile.py

- name: locust-env-cm
  literals:
  - LOCUST_HOST=http://whoami-svc.whoami.svc.cluster.local
