apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
- namespace.yaml
- ingress.yaml
- pv.yaml
- pvc.yaml
- configmap-realm-export.yaml
- ../../../base/keycloak
