apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitnami
spec:
  chart:
    spec:
      chart: redis-cluster
      version: v9.0.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1h
  timeout: 5m
  values:
    existingSecret: redis-secrets
    existingSecretPasswordKey: REDIS_PASSWORD
