apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
spec:
  ports:
  - protocol: TCP
    name: http
    port: 8080
  - protocol: TCP
    name: https
    port: 8443
  selector:
    app: keycloak
