apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  dependsOn:
  - name: is-110-realms
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./provisioning/apps/overlays/k3d-dev
  prune: true
  wait: true
