apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: icinga
spec:
  interval: 30m
  releaseName: icinga-stack
  chart:
    spec:
      chart: icinga-stack
      sourceRef:
        kind: HelmRepository
        name: icinga
      interval: 12h
